language: c
script:
  - ./waf configure --prefix /usr/local
  - ./waf
  - sudo ./waf install
  - ./test.sh
install:
  - sudo add-apt-repository -y ppa:hansjorg/rust
  - sudo apt-get update
  - sudo apt-get install imagemagick rust-nightly
